---
- name: Add Helm repo: jetstack
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install/upgrade cert-manager with CRDs
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    wait: false
    values:
      installCRDs: true

- name: Apply ClusterIssuer
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'templates/clusterissuer.yaml.j2') | from_yaml }}"
